### ISSUE TITLE
I get that when I try to iniciate on heroku

### ISSUE THREAD

**Issue by Asvarius** [Vedza/NitroSniperGo#137]
`2021-01-20T23:22:27.252524+00:00 app[sniper.1]: panic: invalid argument to Intn
2021-01-20T23:22:27.252537+00:00 app[sniper.1]: 
2021-01-20T23:22:27.252537+00:00 app[sniper.1]: goroutine 419 [running]:
2021-01-20T23:22:27.252541+00:00 app[sniper.1]: math/rand.(*Rand).Intn(0xc00009e150, 0x0, 0xc00330c480)
2021-01-20T23:22:27.252566+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go1.12.17/go/src/math/rand/rand.go:169 +0x9c
2021-01-20T23:22:27.252587+00:00 app[sniper.1]: math/rand.Intn(...)
2021-01-20T23:22:27.252605+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go1.12.17/go/src/math/rand/rand.go:329
2021-01-20T23:22:27.252626+00:00 app[sniper.1]: main.messageCreate(0xc00330c480, 0xc00328e118)
2021-01-20T23:22:27.252663+00:00 app[sniper.1]: 	/tmp/build_3063d062_/sniper.go:1004 +0x369
2021-01-20T23:22:27.252718+00:00 app[sniper.1]: github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x842a00, 0xc00330c480, 0x7b78c0, 0xc00328e118)
2021-01-20T23:22:27.252737+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go-path/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x57
2021-01-20T23:22:27.252754+00:00 app[sniper.1]: created by github.com/bwmarrin/discordgo.(*Session).handle
2021-01-20T23:22:27.252793+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go-path/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x111
2021-01-20T23:22:27.321329+00:00 heroku[sniper.1]: Process exited with status 2
2021-01-20T23:22:27.360146+00:00 heroku[sniper.1]: State changed from up to crashed`

**Comment by Asvarius** [comment]
sorry that was entirely my fault
