### ISSUE TITLE
[support] ''Invite'' Function bugged?

### ISSUE THREAD

**Issue by JarnoXCZ** [Vedza/NitroSniperGo#209]
Hello, Vedza.

I don't know If I am understanding this feature incorrectly, but what I think it would do is join random servers via an api.
Or does it join the servers from your main?

Well, even when this function is enabled, It won't join a server.
I hope that you can help me with this.

Thanks, Jarno.

**Comment by PeterStrick** [comment]
> Hello, Vedza.
> 
> I don't know If I am understanding this feature incorrectly, but what I think it would do is join random servers via an api.
> Or does it join the servers from your main?
> 
> Well, even when this function is enabled, It won't join a server.
> I hope that you can help me with this.
> 
> Thanks, Jarno.

Could you maybe set the minimum and maximum delay to either 0 or 1 to see if it works then? For ex, like here:
```
"invite": {
    "enable": true,
    "delay": {
      "min": 1,
      "max": 1
    },
    "max": 99,
    "cooldown": 1
},
```
If it doesn´t, then this might be a bug.

**Comment by DarkGD123** [comment]
There's a bug when the invite function is off it joins a server randomly

**Comment by Vedza** [comment]
There might be some bug on invite sniper, but It's almost impossible that it joins servers randomly when invite sniper is disable

**Comment by iiTrauma** [comment]
maybe your account got locked

**Comment by JarnoXCZ** [comment]
> > Hello, Vedza.
> > I don't know If I am understanding this feature incorrectly, but what I think it would do is join random servers via an api.
> > Or does it join the servers from your main?
> > Well, even when this function is enabled, It won't join a server.
> > I hope that you can help me with this.
> > Thanks, Jarno.
> 
> Could you maybe set the minimum and maximum delay to either 0 or 1 to see if it works then, and then send a Discord Invite per DM/Server message? Config example:
> 
> ```
> "invite": {
>     "enable": true,
>     "delay": {
>       "min": 1,
>       "max": 1
>     },
>     "max": 99,
>     "cooldown": 1
> },
> ```
> 
> If it doesn´t, then this might be a bug.

I have used this config, sent my alt an invite in direct messages, But It didn’t join, even when invite was sent in server.

**Comment by JarnoXCZ** [comment]
Would this be a bug in the in the program or my computer?

**Comment by JarnoXCZ** [comment]
Also, I don't know if this has to do with it but i get this error now:

2021-03-08T16:16:14.477583+00:00 app[sniper.1]: goroutine 220 [running]:
2021-03-08T16:16:14.477584+00:00 app[sniper.1]: math/rand.(*Rand).Intn(0xc00007a150, 0x0, 0xc000a18000)
2021-03-08T16:16:14.477584+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go1.15.8/go/src/math/rand/rand.go:169 +0x9d
2021-03-08T16:16:14.477587+00:00 app[sniper.1]: math/rand.Intn(...)
2021-03-08T16:16:14.477595+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go1.15.8/go/src/math/rand/rand.go:337
2021-03-08T16:16:14.477627+00:00 app[sniper.1]: main.messageCreate(0xc000a18000, 0xc000178778)
2021-03-08T16:16:14.477657+00:00 app[sniper.1]: 	/tmp/build_c24e6ea6_/sniper.go:1011 +0x3be
2021-03-08T16:16:14.477686+00:00 app[sniper.1]: github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x83e3c8, 0xc000a18000, 0x7bfb60, 0xc000178778)
2021-03-08T16:16:14.477690+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go-path/pkg/mod/github.com/bwmarrin/discordgo@v0.23.0/eventhandlers.go:497 +0x4b
2021-03-08T16:16:14.477715+00:00 app[sniper.1]: created by github.com/bwmarrin/discordgo.(*Session).handle
2021-03-08T16:16:14.477748+00:00 app[sniper.1]: 	/tmp/codon/tmp/cache/go-path/pkg/mod/github.com/bwmarrin/discordgo@v0.23.0/event.go:171 +0x111

**Comment by Vedza** [comment]
If there is a bug it comes from the program, and I think you got this error because you put between 1 and 1 minute delay

**Comment by JarnoXCZ** [comment]
IT WORKS! Thank you everyone for helping me!!
