### ISSUE TITLE
Heroku hosting

### ISSUE THREAD

**Issue by FeelsBadMan1** [Vedza/NitroSniperGo#286]
Hello again,
I tried to use the Sniper again after a while but now Heroku just give me some errors that i not understand:
```
2021-05-15T20:22:24.198695+00:00 app[sniper.1]: 
2021-05-15T20:22:24.198824+00:00 app[sniper.1]: goroutine 1 [running]:
2021-05-15T20:22:24.198930+00:00 app[sniper.1]: main.main()
2021-05-15T20:22:24.199085+00:00 app[sniper.1]: 	/tmp/build_1288a36c/sniper.go:676 +0x3d9
2021-05-15T20:22:24.265375+00:00 heroku[sniper.1]: Process exited with status 2
2021-05-15T20:22:24.476187+00:00 heroku[sniper.1]: State changed from up to crashed
2021-05-15T20:22:52.013305+00:00 app[api]: Scaled to sniper@0:Free by user henriksday@gmail.com
2021-05-15T20:22:52.078589+00:00 heroku[sniper.1]: State changed from crashed to down
2021-05-15T20:22:53.086187+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=nitrosniper1337.herokuapp.com request_id=ab6cb602-3730-4ee1-badc-9125fa402c07 fwd="95.90.195.3" dyno= connect= service= status=503 bytes= protocol=https
2021-05-15T20:22:53.527343+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=nitrosniper1337.herokuapp.com request_id=65412490-4652-4d62-9ab2-2258e9e958a8 fwd="95.90.195.3" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by Vedza** [comment]
Hi, I made a huge update a few hours ago that might have some bugs.
Are you using it or do you have and old version ?

**Comment by FeelsBadMan1** [comment]
im using the new version

**Comment by FeelsBadMan1** [comment]
it also would be nice to implement, that if the sniper is enabled to redeem on main that it not join these giveaways with the main and only redeem it there

**Comment by Vedza** [comment]
Can you run it again so I can see the top of the logs ls.
Because I don't have enough informations here

**Comment by Vedza** [comment]
I just found a possible crash and fix it, can you deploy again and tell me if it still crash pls

**Comment by FeelsBadMan1** [comment]
yes now its forking somehow. but still there where some errors before it launched:
```
2021-05-15T20:46:24.588485+00:00 app[sniper.1]: goroutine 1 [running]:
2021-05-15T20:46:24.588574+00:00 app[sniper.1]: main.main()
2021-05-15T20:46:24.588671+00:00 app[sniper.1]: 	/tmp/build_60b0222a/sniper.go:676 +0x3d9
2021-05-15T20:46:24.673480+00:00 heroku[sniper.1]: Process exited with status 2
2021-05-15T20:46:24.813057+00:00 heroku[sniper.1]: State changed from up to crashed
2021-05-15T20:46:25.557479+00:00 app[api]: Scaled to sniper@0:Free by user henriksday@gmail.com
2021-05-15T20:46:25.854518+00:00 heroku[sniper.1]: State changed from crashed to down
2021-05-15T20:46:27.272347+00:00 app[api]: Scaled to sniper@1:Free by user henriksday@gmail.com
2021-05-15T20:46:28.348754+00:00 heroku[sniper.1]: Starting process with command `bin/NitroSniperGo`
2021-05-15T20:46:28.963188+00:00 heroku[sniper.1]: State changed from starting to up
2021-05-15T20:46:33.425691+00:00 app[sniper.1]: 
2021-05-15T20:46:33.425719+00:00 app[sniper.1]: ▓█████▄  ██▓  ██████  ▄████▄   ▒█████   ██▀███  ▓█████▄      ██████  ███▄    █  ██▓ ██▓███  ▓█████  ██▀███
2021-05-15T20:46:33.425719+00:00 app[sniper.1]: ▒██▀ ██▌▓██▒▒██    ▒ ▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▒██▀ ██▌   ▒██    ▒  ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
2021-05-15T20:46:33.425720+00:00 app[sniper.1]: ░██   █▌▒██▒░ ▓██▄   ▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒░██   █▌   ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
2021-05-15T20:46:33.425733+00:00 app[sniper.1]: ░▓█▄   ▌░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ░▓█▄   ▌     ▒   ██▒▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄
2021-05-15T20:46:33.425737+00:00 app[sniper.1]: ░▒████▓ ░██░▒██████▒▒▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▓    ▒██████▒▒▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒
2021-05-15T20:46:33.425741+00:00 app[sniper.1]: ▒▒▓  ▒ ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░ ▒▒▓  ▒    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
2021-05-15T20:46:33.425745+00:00 app[sniper.1]: ░ ▒  ▒  ▒ ░░ ░▒  ░ ░  ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ▒  ▒    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
2021-05-15T20:46:33.425753+00:00 app[sniper.1]: ░ ░  ░  ▒ ░░  ░  ░  ░        ░ ░ ░ ▒    ░░   ░  ░ ░  ░    ░  ░  ░     ░   ░ ░  ▒ ░░░          ░     ░░   ░
2021-05-15T20:46:33.425753+00:00 app[sniper.1]: ░     ░        ░  ░ ░          ░ ░     ░        ░             ░           ░  ░              ░  ░   ░
2021-05-15T20:46:33.425754+00:00 app[sniper.1]: ░                   ░                           ░
2021-05-15T20:46:33.425754+00:00 app[sniper.1]: 	
2021-05-15T20:46:33.614042+00:00 app[sniper.1]: Sniping Discord Nitro and Giveaway for ★MoneyDrop★ on 27 servers and 5 accounts 🔫
2021-05-15T20:46:33.614049+00:00 app[sniper.1]: 
2021-05-15T20:46:33.614106+00:00 app[sniper.1]: 20:46:33 [+] Sniper is ready
```

**Comment by Vedza** [comment]
Ok if it happened on start I think I fixed it. I'll close the issue but if you have that error again after you deploy with the new update I'll reopen it.

**Comment by FeelsBadMan1** [comment]
Thanks for you help. however i noticed some errors still:
```
2021-05-15T20:46:24.588485+00:00 app[sniper.1]: goroutine 1 [running]:
2021-05-15T20:46:24.588574+00:00 app[sniper.1]: main.main()
2021-05-15T20:46:24.588671+00:00 app[sniper.1]: 	/tmp/build_60b0222a/sniper.go:676 +0x3d9
2021-05-15T20:46:24.673480+00:00 heroku[sniper.1]: Process exited with status 2
2021-05-15T20:46:24.813057+00:00 heroku[sniper.1]: State changed from up to crashed
2021-05-15T20:46:25.557479+00:00 app[api]: Scaled to sniper@0:Free by user henriksday@gmail.com
2021-05-15T20:46:25.854518+00:00 heroku[sniper.1]: State changed from crashed to down
2021-05-15T20:46:27.272347+00:00 app[api]: Scaled to sniper@1:Free by user henriksday@gmail.com
2021-05-15T20:46:28.348754+00:00 heroku[sniper.1]: Starting process with command `bin/NitroSniperGo`
2021-05-15T20:46:28.963188+00:00 heroku[sniper.1]: State changed from starting to up
2021-05-15T20:46:33.425691+00:00 app[sniper.1]: 
2021-05-15T20:46:33.425719+00:00 app[sniper.1]: ▓█████▄  ██▓  ██████  ▄████▄   ▒█████   ██▀███  ▓█████▄      ██████  ███▄    █  ██▓ ██▓███  ▓█████  ██▀███
2021-05-15T20:46:33.425719+00:00 app[sniper.1]: ▒██▀ ██▌▓██▒▒██    ▒ ▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▒██▀ ██▌   ▒██    ▒  ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
2021-05-15T20:46:33.425720+00:00 app[sniper.1]: ░██   █▌▒██▒░ ▓██▄   ▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒░██   █▌   ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
2021-05-15T20:46:33.425733+00:00 app[sniper.1]: ░▓█▄   ▌░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ░▓█▄   ▌     ▒   ██▒▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄
2021-05-15T20:46:33.425737+00:00 app[sniper.1]: ░▒████▓ ░██░▒██████▒▒▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▓    ▒██████▒▒▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒
2021-05-15T20:46:33.425741+00:00 app[sniper.1]: ▒▒▓  ▒ ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░ ▒▒▓  ▒    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
2021-05-15T20:46:33.425745+00:00 app[sniper.1]: ░ ▒  ▒  ▒ ░░ ░▒  ░ ░  ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ▒  ▒    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
2021-05-15T20:46:33.425753+00:00 app[sniper.1]: ░ ░  ░  ▒ ░░  ░  ░  ░        ░ ░ ░ ▒    ░░   ░  ░ ░  ░    ░  ░  ░     ░   ░ ░  ▒ ░░░          ░     ░░   ░
2021-05-15T20:46:33.425753+00:00 app[sniper.1]: ░     ░        ░  ░ ░          ░ ░     ░        ░             ░           ░  ░              ░  ░   ░
2021-05-15T20:46:33.425754+00:00 app[sniper.1]: ░                   ░                           ░
2021-05-15T20:46:33.425754+00:00 app[sniper.1]: 	
2021-05-15T20:46:33.614042+00:00 app[sniper.1]: Sniping Discord Nitro and Giveaway for ★MoneyDrop★ on 27 servers and 5 accounts 🔫
2021-05-15T20:46:33.614049+00:00 app[sniper.1]: 
2021-05-15T20:46:33.614106+00:00 app[sniper.1]: 20:46:33 [+] Sniper is ready
2021-05-15T21:25:29.744350+00:00 heroku[sniper.1]: Relocating dyno to a new server
2021-05-15T21:25:29.750679+00:00 heroku[sniper.1]: State changed from up to down
2021-05-15T21:25:29.761710+00:00 heroku[sniper.1]: State changed from down to starting
2021-05-15T21:25:30.785477+00:00 heroku[sniper.1]: Starting process with command `bin/NitroSniperGo`
2021-05-15T21:25:31.566278+00:00 heroku[sniper.1]: State changed from starting to up
2021-05-15T21:25:33.971215+00:00 heroku[sniper.1]: Process exited with status 2
2021-05-15T21:25:34.032043+00:00 heroku[sniper.1]: State changed from up to crashed
2021-05-15T21:25:34.037703+00:00 heroku[sniper.1]: State changed from crashed to starting
2021-05-15T21:25:33.741243+00:00 app[sniper.1]: 
2021-05-15T21:25:33.741254+00:00 app[sniper.1]: ▓█████▄  ██▓  ██████  ▄████▄   ▒█████   ██▀███  ▓█████▄      ██████  ███▄    █  ██▓ ██▓███  ▓█████  ██▀███
2021-05-15T21:25:33.741255+00:00 app[sniper.1]: ▒██▀ ██▌▓██▒▒██    ▒ ▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▒██▀ ██▌   ▒██    ▒  ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
2021-05-15T21:25:33.741255+00:00 app[sniper.1]: ░██   █▌▒██▒░ ▓██▄   ▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒░██   █▌   ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
2021-05-15T21:25:33.741268+00:00 app[sniper.1]: ░▓█▄   ▌░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ░▓█▄   ▌     ▒   ██▒▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄
2021-05-15T21:25:33.741271+00:00 app[sniper.1]: ░▒████▓ ░██░▒██████▒▒▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▓    ▒██████▒▒▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒
2021-05-15T21:25:33.741272+00:00 app[sniper.1]: ▒▒▓  ▒ ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░ ▒▒▓  ▒    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
2021-05-15T21:25:33.741286+00:00 app[sniper.1]: ░ ▒  ▒  ▒ ░░ ░▒  ░ ░  ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ▒  ▒    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
2021-05-15T21:25:33.741287+00:00 app[sniper.1]: ░ ░  ░  ▒ ░░  ░  ░  ░        ░ ░ ░ ▒    ░░   ░  ░ ░  ░    ░  ░  ░     ░   ░ ░  ▒ ░░░          ░     ░░   ░
2021-05-15T21:25:33.741288+00:00 app[sniper.1]: ░     ░        ░  ░ ░          ░ ░     ░        ░             ░           ░  ░              ░  ░   ░
2021-05-15T21:25:33.741289+00:00 app[sniper.1]: ░                   ░                           ░
2021-05-15T21:25:33.741289+00:00 app[sniper.1]: 	
2021-05-15T21:25:33.899294+00:00 app[sniper.1]: Sniping Discord Nitro and Giveawaypanic: runtime error: invalid memory address or nil pointer dereference
2021-05-15T21:25:33.899299+00:00 app[sniper.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e7f59]
2021-05-15T21:25:33.899300+00:00 app[sniper.1]: 
2021-05-15T21:25:33.899327+00:00 app[sniper.1]: goroutine 1 [running]:
2021-05-15T21:25:33.899349+00:00 app[sniper.1]: main.main()
2021-05-15T21:25:33.899377+00:00 app[sniper.1]: 	/tmp/build_60b0222a/sniper.go:676 +0x3d9
2021-05-15T21:25:36.230963+00:00 heroku[sniper.1]: Starting process with command `bin/NitroSniperGo`
2021-05-15T21:25:36.945131+00:00 heroku[sniper.1]: State changed from starting to up
2021-05-15T21:25:44.239780+00:00 heroku[sniper.1]: Process exited with status 2
2021-05-15T21:25:44.407277+00:00 heroku[sniper.1]: State changed from up to crashed
2021-05-15T21:25:43.998340+00:00 app[sniper.1]: 
2021-05-15T21:25:43.998376+00:00 app[sniper.1]: ▓█████▄  ██▓  ██████  ▄████▄   ▒█████   ██▀███  ▓█████▄      ██████  ███▄    █  ██▓ ██▓███  ▓█████  ██▀███
2021-05-15T21:25:43.998377+00:00 app[sniper.1]: ▒██▀ ██▌▓██▒▒██    ▒ ▒██▀ ▀█  ▒██▒  ██▒▓██ ▒ ██▒▒██▀ ██▌   ▒██    ▒  ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
2021-05-15T21:25:43.998377+00:00 app[sniper.1]: ░██   █▌▒██▒░ ▓██▄   ▒▓█    ▄ ▒██░  ██▒▓██ ░▄█ ▒░██   █▌   ░ ▓██▄   ▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
2021-05-15T21:25:43.998379+00:00 app[sniper.1]: ░▓█▄   ▌░██░  ▒   ██▒▒▓▓▄ ▄██▒▒██   ██░▒██▀▀█▄  ░▓█▄   ▌     ▒   ██▒▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄
2021-05-15T21:25:43.998380+00:00 app[sniper.1]: ░▒████▓ ░██░▒██████▒▒▒ ▓███▀ ░░ ████▓▒░░██▓ ▒██▒░▒████▓    ▒██████▒▒▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒
2021-05-15T21:25:43.998382+00:00 app[sniper.1]: ▒▒▓  ▒ ░▓  ▒ ▒▓▒ ▒ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒▓ ░▒▓░ ▒▒▓  ▒    ▒ ▒▓▒ ▒ ░░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
2021-05-15T21:25:43.998384+00:00 app[sniper.1]: ░ ▒  ▒  ▒ ░░ ░▒  ░ ░  ░  ▒     ░ ▒ ▒░   ░▒ ░ ▒░ ░ ▒  ▒    ░ ░▒  ░ ░░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
2021-05-15T21:25:43.998385+00:00 app[sniper.1]: ░ ░  ░  ▒ ░░  ░  ░  ░        ░ ░ ░ ▒    ░░   ░  ░ ░  ░    ░  ░  ░     ░   ░ ░  ▒ ░░░          ░     ░░   ░
2021-05-15T21:25:43.998387+00:00 app[sniper.1]: ░     ░        ░  ░ ░          ░ ░     ░        ░             ░           ░  ░              ░  ░   ░
2021-05-15T21:25:43.998392+00:00 app[sniper.1]: ░                   ░                           ░
2021-05-15T21:25:43.998392+00:00 app[sniper.1]: 	
2021-05-15T21:25:44.161938+00:00 app[sniper.1]: Sniping Discord Nitro and Giveawaypanic: runtime error: invalid memory address or nil pointer dereference
2021-05-15T21:25:44.162071+00:00 app[sniper.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e7f59]
2021-05-15T21:25:44.162091+00:00 app[sniper.1]: 
2021-05-15T21:25:44.162200+00:00 app[sniper.1]: goroutine 1 [running]:
2021-05-15T21:25:44.162256+00:00 app[sniper.1]: main.main()
2021-05-15T21:25:44.162357+00:00 app[sniper.1]: 	/tmp/build_60b0222a/sniper.go:676 +0x3d9
2021-05-15T21:25:50.723077+00:00 heroku[sniper.1]: Stopping all processes with SIGTERM
2021-05-15T21:25:51.526667+00:00 app[sniper.1]: 
2021-05-15T21:25:51.526914+00:00 app[sniper.1]: 
2021-05-15T21:25:51.527000+00:00 app[sniper.1]: 
2021-05-15T21:25:51.527202+00:00 app[sniper.1]: 
2021-05-15T21:25:51.595011+00:00 heroku[sniper.1]: Process exited with status 0
```

**Comment by Vedza** [comment]
have you deleted the dyno and clicked on the heroku button again to have the latest version ?

**Comment by FeelsBadMan1** [comment]
Yes i did that but maybe it where not solved at the point where i have done this. i now try it again

**Comment by FeelsBadMan1** [comment]
Its now started i now need to wait a bit and see if the error appears again or not

**Comment by FeelsBadMan1** [comment]
It not gave out any errors but then it not sniped and not joined servers while the sniper where turned on

**Comment by Vedza** [comment]
Invite sniper is disables but that's normal, but it should sniper code. How many alts do you use ?

**Comment by FeelsBadMan1** [comment]
Hello again. Im using 4 alts and my main so a total of 5 accounts.

**Comment by FeelsBadMan1** [comment]
and i made invitesniper to true but it still not changes anything

**Comment by Vedza** [comment]
Yeah that's normal I disabled it in the code

**Comment by FeelsBadMan1** [comment]
i use 4 alts + my main so a total of 5 accounts. why exaclty the invsiper got disabled?

**Comment by Vedza** [comment]
because it didn't work after discord update
