### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Zedzs** [Vedza/NitroSniperGo#303]
Running Debian 10 (armv8)
The older 3.1 version worked perfectly, but the new v4 build does not work anymore on my pi

Building works without errors, but when running I'm getting this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12408]

goroutine 8 [running]:
runtime/internal/atomic.goXadd64(0x52da114, 0x1, 0x0, 0x511205, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
go.uber.org/atomic.(*Uint64).Add(...)
        /home/nitro/pkg/mod/go.uber.org/atomic@v1.5.1/atomic.go:190
github.com/andersfylling/disgord/internal/gateway.(*client).getLogPrefix(0x52da000, 0x206e000, 0x58)
        /home/nitro/sniper/disgord@custom/internal/gateway/client.go:256 +0x8c
github.com/andersfylling/disgord/internal/gateway.(*client).reconnectLoop(0x52da000, 0x529a6c0, 0x2063cd4)
        /home/nitro/sniper/disgord@custom/internal/gateway/client.go:331 +0x2c
github.com/andersfylling/disgord/internal/gateway.(*shardMngr).Connect(0x52c6000, 0x0, 0x0)
        /home/nitro/sniper/disgord@custom/internal/gateway/sharding.go:323 +0xd8
github.com/andersfylling/disgord.(*Client).Connect(0x20de000, 0x5a4fd0, 0x20ac000, 0x1, 0x0)
        /home/nitro/sniper/disgord@custom/client.go:436 +0x2e4
github.com/andersfylling/disgord.(*Client).StayConnectedUntilInterrupted(0x20de000, 0x5a4fd0, 0x20ac000, 0x5448a00, 0x0)
        /home/nitro/sniper/disgord@custom/client.go:492 +0x44
main.main.func1.1(0x20de000, 0x5a4fd0, 0x20ac000)
        /home/nitro/sniper/sniper.go:591 +0x2c
main.main.func1(0x0, 0x0, 0x20a4fa8)
        /home/nitro/sniper/sniper.go:656 +0x39c
created by main.main
        /home/nitro/sniper/sniper.go:583 +0x168
```

**Comment by andersfylling** [comment]
Seems to be a problem within [disgord](https://github.com/andersfylling/disgord). Or actually the uber atomic package. This could be a fault with using uint64 for arm processors, which has been discussed before. I'll take a look at this later today.
