### ISSUE TITLE
Crash: "panic: runtime error: index out of range [-1]"

### ISSUE THREAD

**Issue by antiops** [Vedza/NitroSniperGo#385]
**Describe the bug**
Sniper crashes throwing error `panic: runtime error: index out of range [-1]`

The `giveaway` & `invite` options in the `settings.json` are set to false. Right before the program closed it said that the user won a giveaway

I am using the linux build from here https://github.com/Vedza/NitroSniperGo/releases/tag/v4.0.2

**Additional context**
```
00:25:02 [+] USERNAME Won Giveaway [SERVER_NAME]
panic: runtime error: index out of range [-1]

goroutine 1761845 [running]:
main.findHost(0x96d498, 0xc0000b6000, 0xc0047e6ba0, 0x1)
        /Users/GolandProjects/NitroSniperGo/sniper.go:864 +0x6cd
main.messageCreate(0x96d498, 0xc0000b6000, 0xc0047e6ba0)
        /Users/GolandProjects/NitroSniperGo/sniper.go:972 +0x751
github.com/andersfylling/disgord.(*dispatcher).trigger(0xc0000b2040, 0x83d740, 0x8fc858, 0x87bde0, 0xc0047e6ba0)
        /Users/GolandProjects/NitroSniperGo/disgord@custom/reactor_gen.go:439 +0x494
github.com/andersfylling/disgord.(*dispatcher).dispatch(0xc0000b2040, 0x965f30, 0xc0000220a0, 0xc0040e6410, 0xe, 0x87bde0, 0xc0047e6ba0)
        /Users/GolandProjects/NitroSniperGo/disgord@custom/reactor.go:154 +0x330
created by github.com/andersfylling/disgord.demultiplexer
        /Users/GolandProjects/NitroSniperGo/disgord@custom/reactor.go:76 +0x279
root@local:~/NitroSniperGo_build_linux# 27142
```

**Comment by andersfylling** [comment]
Seems to be an issue with disgord, though it seems a custom version was used `disgord@custom`. Perhaps this isn't relevant anymore as the switch was made to discordgo?
